import 'dotenv/config';
import * as mongoose from 'mongoose';

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/healthadri';

const MedicineSchema = new mongoose.Schema({
  genericName: String,
  form: String,
  strengths: String,
  cancerTypes: [String],
  brandNames: [String],
  manufacturers: [String],
  drugClass: String,
  category: String,
  notes: String,
}, { timestamps: true });

const Medicine = mongoose.model('Medicine', MedicineSchema);

const MEDICINES = [
  {
    genericName: 'Paclitaxel',
    form: 'Injection',
    strengths: '30mg, 100mg, 260mg',
    cancerTypes: ['Breast', 'Ovarian', 'Lung', 'Pancreatic'],
    brandNames: ['Pacget', 'Mitotax', 'Petaxel', 'INTAXEL', 'Altaxel'],
    manufacturers: ['GLS Pharma', "Dr. Reddy's", 'Zydus Lifesciences', 'Fresenius Kabi', 'Alkem'],
    drugClass: 'Taxane (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Docetaxel',
    form: 'Injection',
    strengths: '20mg, 80mg, 120mg',
    cancerTypes: ['Breast', 'Lung', 'Prostate'],
    brandNames: ['DOCEMAX', 'DOCETAX', 'DOCETERE', 'DTAXANE', 'CELTERE', 'DOCENAT', 'DOXAZ'],
    manufacturers: ['GLS Pharma', 'Cipla', "Dr. Reddy's", 'Torrent', 'Celon', 'Natco', 'Emcure', 'Fresenius Kabi'],
    drugClass: 'Taxane (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Doxorubicin',
    form: 'Injection',
    strengths: '10mg, 50mg',
    cancerTypes: ['Breast', 'Lung', 'Leukemia'],
    brandNames: ['DOXOGET', 'ZUBIDOX', 'DOXOREX', 'DOXIGLAN', 'DUXOCIM', 'DOXOTERO'],
    manufacturers: ['GLS Pharma', 'RPG', 'Samarth Life Science', 'Gland', 'Zydus', 'Hetero'],
    drugClass: 'Anthracycline (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Epirubicin',
    form: 'Injection',
    strengths: '10mg, 50mg, 100mg',
    cancerTypes: ['Breast', 'Gastric', 'Ovarian', 'Lung'],
    brandNames: ['Epithra', 'Epixtra', 'Epitero', 'Rubilon', 'Farmorubicin'],
    manufacturers: ['Glenmark Pharmaceuticals', 'Zydus Ingenxa', 'Hetero', 'Salvavidas Pharma'],
    drugClass: 'Anthracycline (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Pegylated Liposomal Doxorubicin',
    form: 'Injection',
    strengths: '20mg/10ml (2mg/ml)',
    cancerTypes: ['Ovarian', 'Breast', "Kaposi's Sarcoma", 'Multiple Myeloma'],
    brandNames: ['Caelyx', 'Doxil', 'Lipodox', 'Natdox-LP', 'Doxulip', 'Doxosome'],
    manufacturers: ['Janssen (J&J)', 'Sun Pharma (Lipodox)', 'Natco Pharma (Natdox-LP)'],
    drugClass: 'Anthracycline – Liposomal (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Cyclophosphamide',
    form: 'Injection',
    strengths: '200mg, 500mg, 1gm',
    cancerTypes: ['Leukemia', 'Lymphoma', 'Breast'],
    brandNames: ['CTX-GLS', 'CYCLOCEL', 'CYPHOS', 'CYDOXAN', 'UNIPHOS', 'CYCLOXAN'],
    manufacturers: ['GLS Pharma', 'Celon', 'Intas', 'Alkem', 'United Biotech', 'Zydus'],
    drugClass: 'Alkylating Agent (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Ifosfamide',
    form: 'Injection',
    strengths: '500mg, 1gm, 2gm',
    cancerTypes: ['Testicular', 'Ovarian', 'Lung', 'Bladder'],
    brandNames: ['IPOGET', 'CELOFOS', 'IPAMIDE', 'HOLOXAN', 'IFONEON'],
    manufacturers: ['GLS Pharma', 'Celon', 'Cipla', 'Fresenius Kabi', 'Zydus Cadila', 'Neon'],
    drugClass: 'Alkylating Agent (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Bendamustine',
    form: 'Injection',
    strengths: '',
    cancerTypes: ['Leukemia', 'Lymphoma'],
    brandNames: [],
    manufacturers: ["Dr. Reddy's", 'GLS Pharma', 'Torrent'],
    drugClass: 'Alkylating Agent (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Busulfan',
    form: 'Injection & Tablet',
    strengths: '60mg (Inj), 2mg (Tab)',
    cancerTypes: ['Leukemia'],
    brandNames: [],
    manufacturers: ['Celon', 'GLS Pharma', 'Cadila'],
    drugClass: 'Alkylating Agent (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Carmustine',
    form: 'Injection',
    strengths: '100mg',
    cancerTypes: ['Brain Tumors'],
    brandNames: [],
    manufacturers: ['Emcure', 'Khandelwal', 'Therdose', 'GLS Pharma'],
    drugClass: 'Nitrosourea (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Lomustine',
    form: 'Capsule',
    strengths: '10mg, 40mg, 100mg',
    cancerTypes: ["Brain Tumors", "Hodgkin's Lymphoma", 'Lung', 'Skin (Melanoma)'],
    brandNames: ['Lomoother', 'Belustine', 'Gleostine', 'CeeNU', 'Medustine', 'Loomuther'],
    manufacturers: ['Therdose Pharma', 'Cipla (Belustine)', 'Medicon Pharma Lab (Medustine)'],
    drugClass: 'Nitrosourea Alkylating Agent (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Melphalan',
    form: 'Injection & Tablet',
    strengths: '50mg (Inj), 2mg/5mg (Tab)',
    cancerTypes: ['Multiple Myeloma'],
    brandNames: ['MELFALAX', 'ALPHALAN', 'EGYMELAN', 'MEGVAL'],
    manufacturers: [],
    drugClass: 'Alkylating Agent (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Chlorambucil',
    form: 'Tablet',
    strengths: '',
    cancerTypes: ['Leukemia', 'Lymphoma'],
    brandNames: [],
    manufacturers: ['Natco', 'Celon', 'GLS Pharma'],
    drugClass: 'Alkylating Agent (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Cisplatin',
    form: 'Injection',
    strengths: '10mg, 50mg',
    cancerTypes: ['Bladder', 'Ovarian', 'Testicular', 'Lung'],
    brandNames: ['CIZCAN', 'CISMAX', 'CISTERO', 'CELPLAT', 'CISPLAN', 'PLATIN'],
    manufacturers: ['Neon', 'GLS Pharma', 'Hetero', 'Celon', 'Natco', 'Cadila'],
    drugClass: 'Platinum Compound (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Carboplatin',
    form: 'Injection',
    strengths: '150mg, 450mg, 600mg',
    cancerTypes: ['Ovarian', 'Lung', 'Testicular'],
    brandNames: ['CARBOMAX', 'CARBOKEM', 'CARBOPLAN', 'CABOO', 'KARPLAT', 'INNOCAR', 'ONCOCARBIN'],
    manufacturers: ['GLS Pharma', 'Alkem', 'Natco', 'Neon', 'Zydus Cadila', 'BDR', 'Sun'],
    drugClass: 'Platinum Compound (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Oxaliplatin',
    form: 'Injection',
    strengths: '50mg, 100mg',
    cancerTypes: ['Colorectal'],
    brandNames: ['OXIPLAT', 'OXALIMAX', 'OXOPLAN', 'KINAPLAT', 'OXIFECT'],
    manufacturers: ['Sun Pharma', 'GLS Pharma', 'Samarth Life Science', 'Cadila', 'Aureate'],
    drugClass: 'Platinum Compound (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Gemcitabine',
    form: 'Injection',
    strengths: '200mg, 1gm, 1400mg',
    cancerTypes: ['Pancreatic', 'Lung', 'Breast', 'Ovarian', 'Bladder'],
    brandNames: ['Cytogem', 'Gemitrate', 'Gemciglan', 'Gemget', 'Gembine', 'Lifogem', 'Gemibine', 'Gemita'],
    manufacturers: ["Dr. Reddy's", 'Torrent', 'Gland Pharma', 'GLS Pharma', 'Zydus Cadila', 'Samarth Life Science', 'Intas', 'Fresenius Kabi'],
    drugClass: 'Antimetabolite (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Pemetrexed',
    form: 'Injection',
    strengths: '100mg, 500mg',
    cancerTypes: ['Lung', 'Mesothelioma'],
    brandNames: ['PEMNAT', 'SYMYX', 'GIOPEM', 'KABIPEM', 'PAMIGLAN', 'PREXX'],
    manufacturers: ['Natco', 'Biocon', 'GLS Pharma', 'Fresenius Kabi', 'Gland Pharma', 'Celon'],
    drugClass: 'Antimetabolite (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Methotrexate',
    form: 'Injection',
    strengths: '50mg, 500mg, 1gm',
    cancerTypes: ['Leukemia', 'Breast', 'Lung'],
    brandNames: ['METHOCIP', 'METHOFAST', 'REMTREX', 'HITREX', 'PLASTOMET', 'MEREX', 'METHOGET'],
    manufacturers: ['Cipla', 'Neon', 'Alkem', 'VHB', 'Khandelwal', 'Intas', 'GLS Pharma'],
    drugClass: 'Antimetabolite (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Capecitabine',
    form: 'Tablet',
    strengths: '500mg',
    cancerTypes: ['Breast', 'Colorectal', 'Gastric'],
    brandNames: ['Capegard', 'Capsy', 'Xecap', 'Capeta', 'Capecad', 'Capetero', 'Capget'],
    manufacturers: ['Cipla', 'Intas', 'RPG Life Sciences', 'Alkem', 'Cadila', 'Hetero', 'GLS Pharma'],
    drugClass: 'Antimetabolite (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Etoposide',
    form: 'Capsule & Injection',
    strengths: '',
    cancerTypes: ['Lung', 'Testicular'],
    brandNames: [],
    manufacturers: [],
    drugClass: 'Topoisomerase Inhibitor (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'Imatinib',
    form: 'Tablet',
    strengths: '100mg, 400mg',
    cancerTypes: ['CML (Leukemia)'],
    brandNames: [],
    manufacturers: ['Natco', 'Cipla', 'Zydus', 'RPG', 'GLS Pharma'],
    drugClass: 'Tyrosine Kinase Inhibitor (Targeted)',
    category: 'Targeted',
    notes: '',
  },
  {
    genericName: 'Gefitinib',
    form: 'Tablet',
    strengths: '250mg',
    cancerTypes: ['Non-Small Cell Lung'],
    brandNames: ['GEFTIGET', 'GEFTINAT', 'GEFTICIP', 'GEFTISTAR', 'GEFNIB', 'GEFITERO', 'GEFTILON'],
    manufacturers: ['GLS Pharma', 'Natco Pharma', 'Cipla', 'Lupin', 'Glenmark', 'Hetero', 'Celon'],
    drugClass: 'Tyrosine Kinase Inhibitor (Targeted)',
    category: 'Targeted',
    notes: '',
  },
  {
    genericName: 'Erlotinib',
    form: 'Tablet',
    strengths: '100mg, 150mg',
    cancerTypes: ['Lung', 'Pancreatic'],
    brandNames: ['ERLOTIVA', 'ERLOTIREL', 'ERLOTIB', 'TARCEVA', 'ZYCEVA', 'ERLOTEC'],
    manufacturers: ['GLS Pharma', 'Reliance Life Science', 'Intas', 'Roche', 'Zydus Lifesciences', 'United Biotech'],
    drugClass: 'Tyrosine Kinase Inhibitor (Targeted)',
    category: 'Targeted',
    notes: '',
  },
  {
    genericName: 'Temozolomide',
    form: 'Tablet',
    strengths: '20mg, 100mg, 250mg',
    cancerTypes: ['Brain Tumors (Glioblastoma)', 'Anaplastic Astrocytoma'],
    brandNames: ['TEMOGET', 'TEMOSIDE', 'GLIOTEM', 'TEMONAT', 'TEMOZAM', 'TEMOZAD', 'TEMOTIDE'],
    manufacturers: ['GLS Pharma', 'Cipla', 'Sun', 'Natco', 'Fresenius Kabi', 'Adley', 'RPG Lifescience'],
    drugClass: 'Alkylating Agent (Chemotherapy)',
    category: 'Chemotherapy',
    notes: 'Brain tumor specialist',
  },
  {
    genericName: 'Anastrozole',
    form: 'Tablet',
    strengths: '1mg',
    cancerTypes: ['Hormone Receptor+ Breast'],
    brandNames: ['ANASTRONAT', 'FEMISTRA', 'ALTRAZ', 'ANASTROGET', 'ARMOTRAZ', 'ARIMIDEX'],
    manufacturers: ['Natco Pharma', 'Zydus Lifesciences', 'Alkem', 'GLS Pharma', 'Cipla', 'AstraZeneca'],
    drugClass: 'Aromatase Inhibitor (Hormone Therapy)',
    category: 'Hormone Therapy',
    notes: '',
  },
  {
    genericName: 'Exemestane',
    form: 'Tablet',
    strengths: '',
    cancerTypes: ['Hormone Receptor+ Breast'],
    brandNames: [],
    manufacturers: [],
    drugClass: 'Aromatase Inhibitor (Hormone Therapy)',
    category: 'Hormone Therapy',
    notes: '',
  },
  {
    genericName: 'Letrozole',
    form: 'Tablet',
    strengths: '2.5mg',
    cancerTypes: ['Hormone Receptor-Positive Breast Cancer (postmenopausal)'],
    brandNames: ['Femara', 'Letroz', 'Fempro', 'Letril', 'Letisha', 'Letrobella', 'Letrozole'],
    manufacturers: ['Novartis (Femara – originator)', 'Sun Pharma (Letroz)', 'Cipla (Fempro)', 'Zydus Ingenxa (Letisha)'],
    drugClass: 'Aromatase Inhibitor (Hormone Therapy)',
    category: 'Hormone Therapy',
    notes: '',
  },
  {
    genericName: 'Tamoxifen',
    form: 'Tablet',
    strengths: '',
    cancerTypes: ['Breast'],
    brandNames: [],
    manufacturers: [],
    drugClass: 'SERM (Hormone Therapy)',
    category: 'Hormone Therapy',
    notes: '',
  },
  {
    genericName: 'Fulvestrant',
    form: 'Injection',
    strengths: '250mg',
    cancerTypes: ['HR+ Breast (Advanced)'],
    brandNames: ['FUVESTROL', 'FASLODEX', 'FULVIGLEN', 'FULVETRAZ', 'FULZOS', 'FASNORM', 'FASLOMAX'],
    manufacturers: ['Cadila', 'AstraZeneca', 'Glenmark', 'Alkem', 'Hetero', 'Biocon', 'GLS Pharma'],
    drugClass: 'SERD (Hormone Therapy)',
    category: 'Hormone Therapy',
    notes: '',
  },
  {
    genericName: 'Abiraterone',
    form: 'Tablet',
    strengths: '250mg, 500mg',
    cancerTypes: ['Prostate (Advanced)'],
    brandNames: ['ABIRATAS', 'ZELGOR', 'ABSTET', 'ABATITOR', 'ABITATE'],
    manufacturers: ['Intas', 'Sun', 'Biocon', 'Torrent', 'RPG Life Sciences', 'GLS Pharma'],
    drugClass: 'Androgen Synthesis Inhibitor (Hormone Therapy)',
    category: 'Hormone Therapy',
    notes: '',
  },
  {
    genericName: 'Bortezomib',
    form: 'Injection',
    strengths: '1mg, 2mg, 2.5mg, 3.5mg',
    cancerTypes: ['Multiple Myeloma', 'Mantle Cell Lymphoma'],
    brandNames: [],
    manufacturers: ['Natco', 'Janssen', 'Intas', 'Khandelwal', 'Mylan', 'GLS Pharma'],
    drugClass: 'Proteasome Inhibitor (Targeted)',
    category: 'Targeted',
    notes: '',
  },
  {
    genericName: 'Lenalidomide',
    form: 'Capsule',
    strengths: '5mg, 10mg, 15mg, 25mg',
    cancerTypes: ['Multiple Myeloma', 'MDS'],
    brandNames: [],
    manufacturers: ['Natco', "Dr. Reddy's", 'Fresenius Kabi', 'Intas', 'GLS Pharma'],
    drugClass: 'Immunomodulatory (Targeted)',
    category: 'Targeted',
    notes: '',
  },
  {
    genericName: 'Thalidomide',
    form: 'Capsule',
    strengths: '50mg, 100mg, 200mg',
    cancerTypes: ['Multiple Myeloma'],
    brandNames: ['Thalix', 'Thalidomide Celgene', 'Thalomid'],
    manufacturers: ['GLS Pharma', 'Cadila', 'United Biotech', 'Fresenius Kabi', 'Adley', 'Aureate'],
    drugClass: 'Immunomodulatory (Targeted)',
    category: 'Targeted',
    notes: '',
  },
  {
    genericName: 'Hydroxyurea',
    form: 'Capsule',
    strengths: '500mg, 1000mg',
    cancerTypes: ['Blood/Myeloid Cancers'],
    brandNames: [],
    manufacturers: ['Neon', 'Cipla', 'Fresenius Kabi', 'Intas', 'GLS Pharma', 'United Biotech'],
    drugClass: 'Antimetabolite (Chemotherapy)',
    category: 'Chemotherapy',
    notes: '',
  },
  {
    genericName: 'L-Glutamine',
    form: 'Sachet',
    strengths: '',
    cancerTypes: ['Supportive Care'],
    brandNames: [],
    manufacturers: [],
    drugClass: 'Supportive Medication',
    category: 'Supportive',
    notes: 'Side effect management',
  },
];

async function seed() {
  await mongoose.connect(MONGO_URI);
  console.log('Connected to MongoDB');

  const existing = await Medicine.countDocuments();
  if (existing > 0) {
    console.log(`Found ${existing} existing medicines — skipping seed (run with --force to overwrite)`);
    if (!process.argv.includes('--force')) {
      await mongoose.disconnect();
      return;
    }
    await Medicine.deleteMany({});
    console.log('Cleared existing medicines');
  }

  const result = await Medicine.insertMany(MEDICINES);
  console.log(`Seeded ${result.length} medicines`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
